repos:
  ##- repo: https://github.com/psf/black
  ##  rev: 23.11.0
  ##  hooks:
  ##  - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.2.1'
    hooks:
      # linter
      - id: ruff
      # formatter
      - id: ruff-format
