name: docs

on:
  workflow_run:
    workflows: ["tests"]
    branches:
      - master
    types:
      - completed

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: pysetup
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: build
        run: |
          pip install -r requirements_doc.txt

          # sphinx-autodoc needs target package to be installed
          pip install -e .
          cd doc
          sh generate-doc.sh

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # base dir is checkout: /path/to/psweep
          publish_dir: doc/source/_build/html
