name: tests

on:
  push:
    branches:
      - main
      - feature-dask

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: pysetup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install
        run: |
          pip install -e ".[test,dask]"

      - name: run tests
        run: |
          # CI runners have no configured git. Need that for git support tests.
          git config --global user.name "Gaylord Focker"
          git config --global user.email "gl@focker.com"

          # Run parallel tests (-n flag). Detect all $(pwd)/tests/test_*.py
          pytest -n4
